import React, {Component, Fragment} from 'react';

class Index extends Component{
    render(){
        return(
                <div>
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                LOL
                </div>
        )
    }
}

export default Index;